Vagrant.configure(2) do |config|

	config.ssh.insert_key = false
	config.vm.box = "ubuntu/lunar64"
	config.vm.hostname = "ubuntu-nginx"
	config.vm.network "private_network", ip: "192.168.56.60"
	
	config.vm.provision "shell" do |shell|
		shell.path = "01-install-base-tools.sh"
	end
	
	config.vm.provision "shell" do |shell|
		shell.path = "04-install-nmap.sh"
	end
	
	config.vm.provider "virtualbox" do |vb|
		vb.customize ['modifyvm', :id, '--cpus', 1]
		vb.customize ['modifyvm', :id, '--memory', 1024]
	end
	
end